export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//get user details
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

//update user details
export const USER_UPDATE_DETAILS_REQUEST = "USER_UPDATE_DETAILS_REQUEST";
export const USER_UPDATE_DETAILS_SUCCESS = "USER_UPDATE_DETAILS_SUCCESS";
export const USER_UPDATE_DETAILS_FAIL = "USER_UPDATE_DETAILS_FAIL";
export const USER_UPDATE_DETAILS_RESET = "USER_UPDATE_DETAILS_RESET";

export const USER_UPDATE_MENU_REQUEST = "USER_UPDATE_MENU_REQUEST";
export const USER_UPDATE_MENU_SUCCESS = "USER_UPDATE_MENU_SUCCESS";
export const USER_UPDATE_MENU_FAIL = "USER_UPDATE_MENU_FAIL";
export const USER_UPDATE_MENU_RESET = "USER_UPDATE_MENU_RESET";

export const USER_GET_MENU_REQUEST = "USER_GET_MENU_REQUEST";
export const USER_GET_MENU_SUCCESS = "USER_GET_MENU_SUCCESS";
export const USER_GET_MENU_FAIL = "USER_GET_MENU_FAIL";

export const USER_CREATE_MENU_REQUEST = "USER_CREATE_MENU_REQUEST";
export const USER_CREATE_MENU_SUCCESS = "USER_CREATE_MENU_SUCCESS";
export const USER_CREATE_MENU_FAIL = "USER_CREATE_MENU_FAIL";
export const USER_CREATE_MENU_RESET = "USER_CREATE_MENU_RESET";

export const USER_GET_MENU_ITEM_REQUEST = "USER_GET_MENU_ITEM_REQUEST";
export const USER_GET_MENU_ITEM_SUCCESS = "USER_GET_MENU_ITEM_SUCCESS";
export const USER_GET_MENU_ITEM_FAIL = "USER_GET_MENU_ITEM_FAIL";
